version: "3"

services:
  app:
    container_name: server
    build: .
    ports: 
      - 3333:3333
    command: sh -c "npm run migrate && npm run dev"
    volumes: 
      - ./:/usr/app/
    depends_on: 
      - pg
    links: 
      - pg
      
  pg:
    container_name: postgresql
    image: postgres:alpine
    ports: 
      - 5433:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    volumes: 
      - ./data:/var/lib/postgresql/data
