version: "3"

services:
  app:
    container_name: server
    build: .
    ports: 
      - 3333:3333
    command: sh -c "npm run migrate && npm run dev"
    volumes: 
      - ./:/usr/app/
    depends_on: 
      - pg
      - pg-test
    links: 
      - pg
      - pg-test
      
  pg:
    container_name: postgresql
    image: postgres:alpine
    ports: 
      - 5433:5433
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    volumes: 
      - ./data:/var/lib/postgresql/data
  
  pg-test:
    container_name: postgres-test
    image: postgres:alpine
    ports: 
      - 5434:5434
    environment: 
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    